version: '3.8'

services:
  # 우리 데이터베이스 서비스의 이름을 'db'로 지정합니다.
  db:
    # 'docker run' 대신 docker-compose가 이 서비스를 빌드하고 실행하도록 합니다.
    build:
      # Dockerfile이 있는 폴더의 위치를 지정합니다.
      context: ./mysql
    # 컨테이너의 이름을 지정합니다.
    container_name: auth-server
    # 포트 매핑: 내 Mac의 3306 포트와 컨테이너의 3306 포트를 연결합니다.
    ports:
      - "3306:3306"
    # 환경 변수: MySQL root 비밀번호를 설정합니다.
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    # 볼륨 마운트: 데이터 영속성을 위해 DB 데이터를 내 Mac의 폴더와 연결합니다.
    volumes:
      - ~/docker-volumes/mysql:/var/lib/mysql
    # 컨테이너가 항상 재시작되도록 설정합니다.
    restart: always

  redis:
    image: redis:latest
    container_name: auth-redis
    ports:
      - "6379:6379"
    restart: always